name: Generate Resume & Create Release

on:
  push:
    paths:
      - "resume/**"  # Trigger when files in the resume directory are updated
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build Resume and Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate various formats
        run: |
          set -e
          DATE=$(date +"%Y-%m-%d")
          mkdir -p resume/output
          cd resume
          # Build PDF using typst
          docker run --rm \
            -v ${PWD}:/workspace -w /workspace \
            docker.io/danpilch/cv-build:v6 \
            typst compile resume.typ danpilch-resume-${DATE}.pdf
      - name: Create Unique Git Tag
        id: create_tag
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d-%H%M%S")
          TAG="resume-${TIMESTAMP}"
          
          git tag "$TAG"
          git push origin "$TAG"
          echo "tag_name=$TAG" >> $GITHUB_ENV
      - name: Upload All Resumes to Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.tag_name }}
          files: |
            resume/output/danpilch-resume-*.pdf
      - name: Notify Success
        run: echo "Resume files generated and attached to release."
