name: Generate Resume & Create Release

on:
  push:
    paths:
      - "resume/**"
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build Resume and Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Generate various formats
        run: |
          # ... your build steps ...
      
      - name: Replace resume in _posts directory
        run: |
          DATE=$(date +"%Y-%m-%d")
          mv resume/output/danpilch-resume-*.md _posts/*-cv.md
          git mv _posts/*-cv.md _posts/${DATE}-cv.md

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit changes
        run: |
          git add _posts
          git commit -m "Update resume with new date" || echo "No changes to commit"

      - name: Push changes to master
        run: git push origin HEAD:master

      - name: Create Unique Git Tag and push
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d-%H%M%S")
          TAG="resume-${TIMESTAMP}"
          git tag "$TAG"
          git push origin "$TAG"
          echo "tag_name=$TAG" >> $GITHUB_ENV

      - name: Upload All Resumes to Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.tag_name }}
          files: |
            resume/output/danpilch-resume-*.pdf
            resume/output/danpilch-resume-*.html
            resume/output/danpilch-resume-*.css
            resume/output/danpilch-resume-*.md
            resume/output/danpilch-resume-*.docx

      - name: Notify Success
        run: echo "Resume files generated and attached to release."
